version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      OPENAPI_SCHEMA_URL: "http://schema:8001/example-openapi.yml"
      ORIGIN_BASE_URL: "http://localhost:8000"
      ENDPOINT_ALLOW_LIST: "GET:/pets"
    depends_on:
      - schema

  schema:
    image: python:3.12-slim
    command: python -m http.server 8001
    volumes:
      - ./tests/fixtures:/app/tests/fixtures
    working_dir: /app/tests/fixtures
    ports:
      - "8001:8001"
