name: Integration Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.x"

      - name: Start the fixture server
        run: docker compose up schema -d
    
      - name: Run unit tests
        run: uv run pytest tests/integration        